language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

before_install:
  openssl aes-256-cbc -K $encrypted_c1783f0e2b2b_key -iv $encrypted_c1783f0e2b2b_iv -in app/google-services.json.enc -out app/google-services.json -d